name: Ejecutar script cada 20 minutos

on:
  # Ejecutar cada 20 minutos
  schedule:
    - cron: '*/20 * * * *'

  # Ejecutar en push events
  push:
    branches: [ main ]

  # Ejecutar en pull request events
  pull_request:
    types: [opened, synchronize]

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/checkout@v4
      with:
        python-version: '3.x'
    
    - name: autocomit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Changed files
        push_options: '--force'
    - name: Instalar dependencias
      run: |
        python -m pip install setuptools
        python -m pip install --upgrade pip
        pip install -r requirements.txt         

    - name: Ejecutar script Python
      run: |
        python Download_data.py
