name: Ejecutar script cada 20 minutos

on:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Ejecutar script Python
      run: |
        python Download_data.py
